Repository inexorgame/vulkan-renderer, pull requests merged in 2020-05, with the labels that each got.

#149 [cmake] Cleanup
  CMakeLists.txt
  benchmarks/CMakeLists.txt
  example/CMakeLists.txt
  src/CMakeLists.txt
  tests/CMakeLists.txt
Labels: cmake

#144 [ci] Use Ubuntu 20.04
  .github/workflows/build.yml
  README.rst
Labels: github-actions

#152 Remove shader manager and implement RAII idiom for shaders.
  include/inexor/vulkan-renderer/application.hpp
  include/inexor/vulkan-renderer/renderer.hpp
  include/inexor/vulkan-renderer/shader.hpp
  include/inexor/vulkan-renderer/shader_manager.hpp
  src/CMakeLists.txt
  src/vulkan-renderer/application.cpp
  src/vulkan-renderer/renderer.cpp
  src/vulkan-renderer/shader.cpp
  src/vulkan-renderer/shader_manager.cpp
Labels: RAII, refactoring, shaders

#153 [code] Cleanup ThreadPool templates
  include/inexor/vulkan-renderer/thread_pool.hpp
Labels: multithreading, refactoring

#158 [conan] Get benchmark and tests dependencies only if required
  cmake/conan_setup.cmake
  conanfile.py
Labels: benchmark, refactoring

#160 Use RAII for shaders, gpu memory buffers, staging buffers, mesh buffers and textures.
  include/inexor/vulkan-renderer/application.hpp
  include/inexor/vulkan-renderer/gltf-model/animation.hpp
  include/inexor/vulkan-renderer/gltf-model/animation_channel.hpp
  include/inexor/vulkan-renderer/gltf-model/animation_sampler.hpp
  include/inexor/vulkan-renderer/gltf-model/bounding_box.hpp
  include/inexor/vulkan-renderer/gltf-model/dimensions.hpp
  include/inexor/vulkan-renderer/gltf-model/manager.hpp
  include/inexor/vulkan-renderer/gltf-model/material.hpp
  include/inexor/vulkan-renderer/gltf-model/mesh.hpp
  include/inexor/vulkan-renderer/gltf-model/model.hpp
  include/inexor/vulkan-renderer/gltf-model/node.hpp
  include/inexor/vulkan-renderer/gltf-model/primitive.hpp
  include/inexor/vulkan-renderer/gltf-model/skin.hpp
  include/inexor/vulkan-renderer/gltf-model/texture_sampler.hpp
  include/inexor/vulkan-renderer/gltf-model/uniform_buffer.hpp
  include/inexor/vulkan-renderer/gltf-model/vertex.hpp
  include/inexor/vulkan-renderer/gpu_memory_buffer.hpp
  include/inexor/vulkan-renderer/mesh_buffer.hpp
  include/inexor/vulkan-renderer/mesh_buffer_manager.hpp
  include/inexor/vulkan-renderer/octree_vertex.hpp
  include/inexor/vulkan-renderer/once_command_buffer.hpp
  include/inexor/vulkan-renderer/renderer.hpp
  include/inexor/vulkan-renderer/shader.hpp
  include/inexor/vulkan-renderer/single_time_command_buffer.hpp
  include/inexor/vulkan-renderer/staging_buffer.hpp
  include/inexor/vulkan-renderer/texture.hpp
  include/inexor/vulkan-renderer/texture_manager.hpp
  include/inexor/vulkan-renderer/uniform_buffer.hpp
  include/inexor/vulkan-renderer/uniform_buffer_manager.hpp
  shaders/fragmentshader.frag
  shaders/vertexshader.vert
  src/CMakeLists.txt
  src/vulkan-renderer/application.cpp
  src/vulkan-renderer/gltf-model/bounding_box.cpp
  src/vulkan-renderer/gltf-model/manager.cpp
  src/vulkan-renderer/gltf-model/mesh.cpp
  src/vulkan-renderer/gltf-model/node.cpp
  src/vulkan-renderer/gltf-model/primitive.cpp
  src/vulkan-renderer/gltf-model/vertex.cpp
  src/vulkan-renderer/gpu_memory_buffer.cpp
  src/vulkan-renderer/mesh_buffer.cpp
  src/vulkan-renderer/mesh_buffer_manager.cpp
  src/vulkan-renderer/octree_vertex.cpp
  src/vulkan-renderer/once_command_buffer.cpp
  src/vulkan-renderer/renderer.cpp
  src/vulkan-renderer/single_time_command_buffer.cpp
  src/vulkan-renderer/staging_buffer.cpp
  src/vulkan-renderer/texture.cpp
  src/vulkan-renderer/texture_manager.cpp
  src/vulkan-renderer/uniform_buffer.cpp
  src/vulkan-renderer/uniform_buffer_manager.cpp
Labels: RAII, refactoring

#163 [refactoring] Make adequate use of [[nodiscard]] attribute.
  include/inexor/vulkan-renderer/availability_checks.hpp
  include/inexor/vulkan-renderer/bezier_curve.h
  include/inexor/vulkan-renderer/error_handling.hpp
  include/inexor/vulkan-renderer/fence_manager.hpp
  include/inexor/vulkan-renderer/gpu_memory_buffer.hpp
  include/inexor/vulkan-renderer/gpu_queue_manager.hpp
  include/inexor/vulkan-renderer/mesh_buffer.hpp
  include/inexor/vulkan-renderer/octree_vertex.hpp
  include/inexor/vulkan-renderer/once_command_buffer.hpp
  include/inexor/vulkan-renderer/semaphore_manager.hpp
  include/inexor/vulkan-renderer/settings_decision_maker.hpp
  include/inexor/vulkan-renderer/shader.hpp
  include/inexor/vulkan-renderer/texture.hpp
  include/inexor/vulkan-renderer/time_step.hpp
  include/inexor/vulkan-renderer/tools/cla_parser.hpp
  include/inexor/vulkan-renderer/tools/file.hpp
Labels: difficulty: easy, refactoring

#161 Replace descriptor manager with an RAII wrapper class.
  include/inexor/vulkan-renderer/descriptor.hpp
  include/inexor/vulkan-renderer/descriptor_bundle.hpp
  include/inexor/vulkan-renderer/descriptor_manager.hpp
  include/inexor/vulkan-renderer/descriptor_pool.hpp
  include/inexor/vulkan-renderer/renderer.hpp
  src/CMakeLists.txt
  src/vulkan-renderer/application.cpp
  src/vulkan-renderer/descriptor.cpp
  src/vulkan-renderer/descriptor_manager.cpp
  src/vulkan-renderer/descriptor_pool.cpp
  src/vulkan-renderer/renderer.cpp
Labels: RAII, refactoring

#164 VkInstance RAII wrapper refactoring.
  include/inexor/vulkan-renderer/renderer.hpp
  include/inexor/vulkan-renderer/wrapper/instance.hpp
  src/CMakeLists.txt
  src/vulkan-renderer/application.cpp
  src/vulkan-renderer/renderer.cpp
  src/vulkan-renderer/wrapper/instance.cpp
Labels: RAII, refactoring

#165 Conan cmake update
  cmake/conan_setup.cmake
Labels: cmake, feature

#166 [bezier] Fix using the wrong glm length
  src/vulkan-renderer/bezier_curve.cpp
Labels: bezier-curves, bugfix, dependency: glm

#167 VkDevice/VkPhysicalDevice/VkQueue RAII wrapper refactoring.
  include/inexor/vulkan-renderer/gpu_queue_manager.hpp
  include/inexor/vulkan-renderer/renderer.hpp
  include/inexor/vulkan-renderer/settings_decision_maker.hpp
  include/inexor/vulkan-renderer/wrapper/device.hpp
  src/CMakeLists.txt
  src/vulkan-renderer/application.cpp
  src/vulkan-renderer/gpu_queue_manager.cpp
  src/vulkan-renderer/renderer.cpp
  src/vulkan-renderer/settings_decision_maker.cpp
  src/vulkan-renderer/wrapper/device.cpp
Labels: RAII, refactoring

#168 Cleanup command line parser
  example/main.cpp
  include/inexor/vulkan-renderer/application.hpp
  include/inexor/vulkan-renderer/tools/cla_parser.hpp
  src/vulkan-renderer/application.cpp
  src/vulkan-renderer/tools/cla_parser.cpp
Labels: refactoring

#170 [example] Remove process id from log
  example/main.cpp
Labels: dependency: spdlog, refactoring

#169 VMA RAII wrapper refactoring.
  include/inexor/vulkan-renderer/renderer.hpp
  include/inexor/vulkan-renderer/wrapper/vma.hpp
  src/CMakeLists.txt
  src/vulkan-renderer/application.cpp
  src/vulkan-renderer/renderer.cpp
  src/vulkan-renderer/wrapper/vma.cpp
Labels: RAII, refactoring

#173 Swapchain RAII wrapper refactoring.
  include/inexor/vulkan-renderer/renderer.hpp
  include/inexor/vulkan-renderer/settings_decision_maker.hpp
  include/inexor/vulkan-renderer/wrapper/swapchain.hpp
  src/CMakeLists.txt
  src/vulkan-renderer/application.cpp
  src/vulkan-renderer/renderer.cpp
  src/vulkan-renderer/settings_decision_maker.cpp
  src/vulkan-renderer/wrapper/swapchain.cpp
Labels: RAII, refactoring

#174 [shaders] Remove GL_ARB_separate_shader_objects
  shaders/fragmentshader.frag
  shaders/vertexshader.vert
Labels: cleanup

#176 Remove volk metaloader library from third_party folder.
  third_party/volk/LICENSE.md
  third_party/volk/volk.c
  third_party/volk/volk.h
Labels: cleanup

#175 [doc] Add labeling
  documentation/source/development/design/labeling.rst
  documentation/source/development/design/main.rst
Labels: cleanup

#178 Window and surface RAII wrapper refactoring.
  include/inexor/vulkan-renderer/renderer.hpp
  include/inexor/vulkan-renderer/wrapper/glfw_context.hpp
  include/inexor/vulkan-renderer/wrapper/window.hpp
  include/inexor/vulkan-renderer/wrapper/window_surface.hpp
  src/CMakeLists.txt
  src/vulkan-renderer/application.cpp
  src/vulkan-renderer/renderer.cpp
  src/vulkan-renderer/wrapper/glfw_context.cpp
  src/vulkan-renderer/wrapper/window.cpp
  src/vulkan-renderer/wrapper/window_surface.cpp
Labels: cat:refactor

#179 VkCommandPool RAII wrapper refactoring.
  include/inexor/vulkan-renderer/once_command_buffer.hpp
  include/inexor/vulkan-renderer/renderer.hpp
  include/inexor/vulkan-renderer/wrapper/command_pool.hpp
  src/CMakeLists.txt
  src/vulkan-renderer/application.cpp
  src/vulkan-renderer/once_command_buffer.cpp
  src/vulkan-renderer/renderer.cpp
  src/vulkan-renderer/wrapper/command_pool.cpp
Labels: cat:refactor

#180 VkCommandBuffer RAII wrapper refactoring.
  include/inexor/vulkan-renderer/once_command_buffer.hpp
  include/inexor/vulkan-renderer/renderer.hpp
  include/inexor/vulkan-renderer/wrapper/command_buffer.hpp
  include/inexor/vulkan-renderer/wrapper/command_pool.hpp
  src/CMakeLists.txt
  src/vulkan-renderer/application.cpp
  src/vulkan-renderer/once_command_buffer.cpp
  src/vulkan-renderer/renderer.cpp
  src/vulkan-renderer/wrapper/command_buffer.cpp
Labels: cat:refactor

#182 VkImage and VkImageView RAII wrapper refactoring.
  include/inexor/vulkan-renderer/image_buffer.hpp
  include/inexor/vulkan-renderer/msaa_target.hpp
  include/inexor/vulkan-renderer/renderer.hpp
  include/inexor/vulkan-renderer/texture.hpp
  include/inexor/vulkan-renderer/wrapper/image.hpp
  src/CMakeLists.txt
  src/vulkan-renderer/renderer.cpp
  src/vulkan-renderer/texture.cpp
  src/vulkan-renderer/wrapper/image.cpp
Labels: cat:refactor

#184 VkFence and VkSemaphore RAII wrapper refactoring.
  include/inexor/vulkan-renderer/fence_manager.hpp
  include/inexor/vulkan-renderer/msaa_target.hpp
  include/inexor/vulkan-renderer/renderer.hpp
  include/inexor/vulkan-renderer/semaphore_manager.hpp
  include/inexor/vulkan-renderer/wrapper/fence.hpp
  include/inexor/vulkan-renderer/wrapper/semaphore.hpp
  src/CMakeLists.txt
  src/vulkan-renderer/application.cpp
  src/vulkan-renderer/fence_manager.cpp
  src/vulkan-renderer/renderer.cpp
  src/vulkan-renderer/semaphore_manager.cpp
  src/vulkan-renderer/wrapper/fence.cpp
  src/vulkan-renderer/wrapper/semaphore.cpp
Labels: cat:refactor

#185 Vulkan pipeline RAII wrapper refactoring.
  include/inexor/vulkan-renderer/octree_vertex.hpp
  include/inexor/vulkan-renderer/renderer.hpp
  include/inexor/vulkan-renderer/wrapper/graphics_pipeline.hpp
  include/inexor/vulkan-renderer/wrapper/pipeline_layout.hpp
  include/inexor/vulkan-renderer/wrapper/renderpass.hpp
  src/CMakeLists.txt
  src/vulkan-renderer/octree_vertex.cpp
  src/vulkan-renderer/renderer.cpp
  src/vulkan-renderer/wrapper/graphics_pipeline.cpp
  src/vulkan-renderer/wrapper/pipeline_layout.cpp
  src/vulkan-renderer/wrapper/renderpass.cpp
Labels: cat:refactor

#186 VkFramebuffer RAII wrapper refactoring.
  include/inexor/vulkan-renderer/renderer.hpp
  include/inexor/vulkan-renderer/wrapper/framebuffer.hpp
  include/inexor/vulkan-renderer/wrapper/swapchain.hpp
  src/CMakeLists.txt
  src/vulkan-renderer/renderer.cpp
  src/vulkan-renderer/wrapper/framebuffer.cpp
Labels: cat:refactor
