Repository inexorgame/vulkan-renderer, pull requests merged in 2021-03, with the labels that each got.

#323 [ci] Add commit naming check
  .github/workflows/commit_naming.yml
  helper/gitcc/gitcc/__init__.py
  helper/gitcc/gitcc/main.py
  helper/gitcc/gitcc/utility.py
  helper/gitcc/setup.py
Labels: feat:ci, org:review

#326 [dep] Use VMA and vulkan-headers from conan
  conanfile.py
  include/inexor/vulkan-renderer/frame_graph.hpp
  include/inexor/vulkan-renderer/wrapper/device.hpp
  include/inexor/vulkan-renderer/wrapper/gpu_memory_buffer.hpp
  include/inexor/vulkan-renderer/wrapper/image.hpp
  include/inexor/vulkan-renderer/wrapper/mesh_buffer.hpp
  src/vulkan-renderer/frame_graph.cpp
  src/vulkan-renderer/wrapper/device.cpp
  src/vulkan-renderer/wrapper/gpu_texture.cpp
  third_party/.gitkeep
  third_party/vma/LICENSE.txt
  third_party/vma/vk_mem_alloc.h
  third_party/vma/vma_usage.cpp
  third_party/vma/vma_usage.h
Labels: cat:dependency, org:review

#325 [doc] Fix documentation building
  include/inexor/vulkan-renderer/debug_callback.hpp
  include/inexor/vulkan-renderer/wrapper/make_info.hpp
Labels: cat:documentation, org:review, prio:high

#327 [wrapper] Make sure to zero-out VMA structs
  include/inexor/vulkan-renderer/wrapper/gpu_memory_buffer.hpp
Labels: prio:blocker
