Repository inexorgame/vulkan-renderer, pull requests merged in 2021-06, with the labels that each got.

#321 [collision] First generation of octree collision detection
  benchmarks/CMakeLists.txt
  benchmarks/world/cube_collision.cpp
  conanfile.py
  documentation/source/development/building.rst
  documentation/source/development/reference/main.rst
  documentation/source/development/reference/octree-collision.rst
  documentation/source/development/reference/octree-file-format.rst
  documentation/source/development/reference/octree_collision_boundin_sphere_false_positive.jpg
  documentation/source/development/reference/octree_collision_camera_view_blocked.jpg
  documentation/source/development/reference/octree_collision_cases.jpg
  documentation/source/development/reference/octree_collision_cube_facing_camera.jpg
  documentation/source/development/reference/octree_collision_filled.jpg
  documentation/source/development/reference/octree_collision_multiple_octrees.jpg
  documentation/source/development/reference/octree_collision_nearest_corner.jpg
  documentation/source/development/reference/octree_collision_octant.jpg
  documentation/source/development/reference/octree_collision_only_front_collisions.jpg
  documentation/source/development/reference/octree_collision_real_face.jpg
  documentation/source/development/reference/octree_collision_sizes.jpg
  include/inexor/vulkan-renderer/application.hpp
  include/inexor/vulkan-renderer/world/collision.hpp
  include/inexor/vulkan-renderer/world/collision_query.hpp
  include/inexor/vulkan-renderer/world/cube.hpp
  src/CMakeLists.txt
  src/vulkan-renderer/application.cpp
  src/vulkan-renderer/renderer.cpp
  src/vulkan-renderer/world/collision.cpp
  src/vulkan-renderer/world/collision_query.cpp
  tests/CMakeLists.txt
  tests/unit_tests_main.cpp
  tests/world/cube_collision.cpp
Labels: cat:enhancement, diff:advanced, feat:octree, org:in progress

#322 Added configurable window modes
  configuration/renderer.toml
  include/inexor/vulkan-renderer/renderer.hpp
  include/inexor/vulkan-renderer/wrapper/window.hpp
  src/vulkan-renderer/application.cpp
  src/vulkan-renderer/wrapper/window.cpp
Labels: feat:rendering, feat:settings, org:ready to merge

#401 [input] Refactoring
  documentation/source/development/reference/keyboard-mouse-input.rst
  include/inexor/vulkan-renderer/input/keyboard_mouse_data.hpp
  src/vulkan-renderer/input/keyboard_mouse_data.cpp
Labels: cat:refactor

#378 [representation|gpu-info] Refactoring
  include/inexor/vulkan-renderer/exception.hpp
  include/inexor/vulkan-renderer/vk_tools/representation.hpp
  src/vulkan-renderer/exception.cpp
  src/vulkan-renderer/vk_tools/gpu_info.cpp
  src/vulkan-renderer/vk_tools/representation.cpp
Labels: cat:refactor
