Repository inexorgame/vulkan-renderer, pull requests merged in 2021-04, with the labels that each got.

#350 [gpu-info] Don't use exceptions in gpu info
  src/vulkan-renderer/vk_tools/gpu_info.cpp
Labels: cat:bug, cat:refactor

#353 [gpu-info] Don't display empty gpu info queries as error
  src/vulkan-renderer/vk_tools/gpu_info.cpp
Labels: cat:refactor

#354 [destructors] Remove unnecessary spdlog messages
  src/vulkan-renderer/imgui.cpp
  src/vulkan-renderer/wrapper/cpu_texture.cpp
  src/vulkan-renderer/wrapper/descriptor.cpp
  src/vulkan-renderer/wrapper/device.cpp
  src/vulkan-renderer/wrapper/fence.cpp
  src/vulkan-renderer/wrapper/framebuffer.cpp
  src/vulkan-renderer/wrapper/glfw_context.cpp
  src/vulkan-renderer/wrapper/gpu_memory_buffer.cpp
  src/vulkan-renderer/wrapper/gpu_texture.cpp
  src/vulkan-renderer/wrapper/graphics_pipeline.cpp
  src/vulkan-renderer/wrapper/image.cpp
  src/vulkan-renderer/wrapper/instance.cpp
  src/vulkan-renderer/wrapper/renderpass.cpp
  src/vulkan-renderer/wrapper/semaphore.cpp
  src/vulkan-renderer/wrapper/shader.cpp
  src/vulkan-renderer/wrapper/swapchain.cpp
  src/vulkan-renderer/wrapper/window.cpp
  src/vulkan-renderer/wrapper/window_surface.cpp
Labels: cat:refactor

#352 Add documentation building to ci and update the documentation
  .github/workflows/build_documentation.yml
  documentation/CMakeLists.txt
  documentation/requirements.txt
  documentation/source/conf.py
  documentation/source/development/building.rst
  documentation/source/development/engine-design/code-design.rst
  documentation/source/development/engine-design/dependencies.rst
  documentation/source/development/getting-started.rst
  documentation/source/links/main.rst
  helper/requirements_check/req_check.py
Labels: cat:documentation, cat:refactor, feat:ci

#356 [destructors] Remove unnecessary if checks
  src/vulkan-renderer/wrapper/command_pool.cpp
  src/vulkan-renderer/wrapper/cpu_texture.cpp
  src/vulkan-renderer/wrapper/descriptor.cpp
  src/vulkan-renderer/wrapper/device.cpp
  src/vulkan-renderer/wrapper/fence.cpp
  src/vulkan-renderer/wrapper/framebuffer.cpp
  src/vulkan-renderer/wrapper/glfw_context.cpp
  src/vulkan-renderer/wrapper/gpu_memory_buffer.cpp
  src/vulkan-renderer/wrapper/gpu_texture.cpp
  src/vulkan-renderer/wrapper/image.cpp
  src/vulkan-renderer/wrapper/instance.cpp
  src/vulkan-renderer/wrapper/semaphore.cpp
  src/vulkan-renderer/wrapper/shader.cpp
  src/vulkan-renderer/wrapper/swapchain.cpp
  src/vulkan-renderer/wrapper/window.cpp
  src/vulkan-renderer/wrapper/window_surface.cpp
Labels: cat:refactor

#369 [octree] Fix parent bugs
  include/inexor/vulkan-renderer/world/cube.hpp
  src/vulkan-renderer/application.cpp
  src/vulkan-renderer/world/cube.cpp
Labels: cat:refactor, feat:octree, org:ready to merge

#363 Iceflower/ci fox
  .github/workflows/build.yml
  .github/workflows/code_style.yml
  .github/workflows/commit_naming.yml
  helper/gitcc/gitcc/utility.py
Labels: cat:dev tools, feat:ci, org:ready to merge

#373 [ci] Fix documentation build
  .github/workflows/build_documentation.yml
Labels: cat:dev tools

#377 [gpu-info] Cleanup
  include/inexor/vulkan-renderer/vk_tools/gpu_info.hpp
  include/inexor/vulkan-renderer/vk_tools/representation.hpp
  src/vulkan-renderer/vk_tools/gpu_info.cpp
  src/vulkan-renderer/vk_tools/representation.cpp
Labels: cat:refactor
