Repository inexorgame/vulkan-renderer, pull requests merged in 2022-09, with the labels that each got.

#485 [ci] Improve git commit check
  .github/workflows/commit_naming.yml
  helper/commit_validator.mjs
  helper/gitcc/gitcc/__init__.py
  helper/gitcc/gitcc/git_hook.py
  helper/gitcc/gitcc/git_hooks/__init__.py
  helper/gitcc/gitcc/git_hooks/commit_msg_summary.py
  helper/gitcc/gitcc/main.py
  helper/gitcc/gitcc/utility.py
  helper/gitcc/setup.py
Labels: cat:enhancement, feat:ci

#483 Use Vulkan Memory Allocator 3.0.1 and switch to Vulkan 1.3 for continuous integration
  .github/workflows/build.yml
  CMakeLists.txt
  conanfile.py
  documentation/source/development/building.rst
  example/main.cpp
  include/inexor/vulkan-renderer/renderer.hpp
  src/CMakeLists.txt
  src/vulkan-renderer/render_graph.cpp
  src/vulkan-renderer/renderer.cpp
  src/vulkan-renderer/wrapper/device.cpp
  src/vulkan-renderer/wrapper/gpu_memory_buffer.cpp
  src/vulkan-renderer/wrapper/image.cpp
  vma-dumps/GpuMemDumpVis.py
  vma-dumps/README.md
  vma-dumps/VmaDumpVis.py
  vma-replays/vma-replays.txt
Labels: cat:refactor

#472 Refactor management of command pools, command buffers, staging buffers, and remove once command buffer
  documentation/source/development/reference/command-buffers-and-command-pools.rst
  documentation/source/development/reference/main.rst
  include/inexor/vulkan-renderer/render_graph.hpp
  include/inexor/vulkan-renderer/renderer.hpp
  include/inexor/vulkan-renderer/wrapper/command_buffer.hpp
  include/inexor/vulkan-renderer/wrapper/command_pool.hpp
  include/inexor/vulkan-renderer/wrapper/descriptor.hpp
  include/inexor/vulkan-renderer/wrapper/descriptor_builder.hpp
  include/inexor/vulkan-renderer/wrapper/device.hpp
  include/inexor/vulkan-renderer/wrapper/fence.hpp
  include/inexor/vulkan-renderer/wrapper/gpu_memory_buffer.hpp
  include/inexor/vulkan-renderer/wrapper/gpu_texture.hpp
  include/inexor/vulkan-renderer/wrapper/mesh_buffer.hpp
  include/inexor/vulkan-renderer/wrapper/once_command_buffer.hpp
  include/inexor/vulkan-renderer/wrapper/staging_buffer.hpp
  include/inexor/vulkan-renderer/wrapper/swapchain.hpp
  src/CMakeLists.txt
  src/vulkan-renderer/application.cpp
  src/vulkan-renderer/imgui.cpp
  src/vulkan-renderer/render_graph.cpp
  src/vulkan-renderer/renderer.cpp
  src/vulkan-renderer/wrapper/command_buffer.cpp
  src/vulkan-renderer/wrapper/command_pool.cpp
  src/vulkan-renderer/wrapper/descriptor.cpp
  src/vulkan-renderer/wrapper/descriptor_builder.cpp
  src/vulkan-renderer/wrapper/device.cpp
  src/vulkan-renderer/wrapper/fence.cpp
  src/vulkan-renderer/wrapper/gpu_memory_buffer.cpp
  src/vulkan-renderer/wrapper/gpu_texture.cpp
  src/vulkan-renderer/wrapper/make_info.cpp
  src/vulkan-renderer/wrapper/once_command_buffer.cpp
  src/vulkan-renderer/wrapper/staging_buffer.cpp
  src/vulkan-renderer/wrapper/swapchain.cpp
Labels: cat:refactor

#487 Use C++20's designated initializers
  include/inexor/vulkan-renderer/wrapper/descriptor_builder.hpp
  include/inexor/vulkan-renderer/wrapper/gpu_memory_buffer.hpp
  include/inexor/vulkan-renderer/wrapper/make_info.hpp
  src/vulkan-renderer/imgui.cpp
  src/vulkan-renderer/render_graph.cpp
  src/vulkan-renderer/renderer.cpp
  src/vulkan-renderer/wrapper/command_buffer.cpp
  src/vulkan-renderer/wrapper/command_pool.cpp
  src/vulkan-renderer/wrapper/descriptor.cpp
  src/vulkan-renderer/wrapper/descriptor_builder.cpp
  src/vulkan-renderer/wrapper/device.cpp
  src/vulkan-renderer/wrapper/fence.cpp
  src/vulkan-renderer/wrapper/framebuffer.cpp
  src/vulkan-renderer/wrapper/gpu_memory_buffer.cpp
  src/vulkan-renderer/wrapper/gpu_texture.cpp
  src/vulkan-renderer/wrapper/image.cpp
  src/vulkan-renderer/wrapper/instance.cpp
  src/vulkan-renderer/wrapper/make_info.cpp
  src/vulkan-renderer/wrapper/semaphore.cpp
  src/vulkan-renderer/wrapper/shader.cpp
  src/vulkan-renderer/wrapper/swapchain.cpp
Labels: cat:refactor

#490 Added build instructions for Fedora
  documentation/source/development/building.rst
Labels: cat:documentation

#489 Implement improved physical device selection
  documentation/source/development/reference/gpu-selection.rst
  documentation/source/development/reference/gpu_selection_mechanism.svg
  include/inexor/vulkan-renderer/application.hpp
  include/inexor/vulkan-renderer/settings_decision_maker.hpp
  include/inexor/vulkan-renderer/vk_tools/device_info.hpp
  include/inexor/vulkan-renderer/vk_tools/enumerate.hpp
  include/inexor/vulkan-renderer/vk_tools/representation.hpp
  include/inexor/vulkan-renderer/wrapper/device.hpp
  src/CMakeLists.txt
  src/vulkan-renderer/application.cpp
  src/vulkan-renderer/settings_decision_maker.cpp
  src/vulkan-renderer/vk_tools/device_info.cpp
  src/vulkan-renderer/vk_tools/enumerate.cpp
  src/vulkan-renderer/vk_tools/representation.cpp
  src/vulkan-renderer/wrapper/device.cpp
  src/vulkan-renderer/wrapper/gpu_texture.cpp
  tests/CMakeLists.txt
  tests/gpu-selection/selection.cpp
Labels: cat:refactor

#492 Add latest development release
  .github/workflows/build.yml
  .github/workflows/build_documentation.yml
  .github/workflows/release.yml
  .github/workflows/static_analysis.yml
  CMakeLists.txt
  conanfile.py
  helper/req_check.py
  include/inexor/vulkan-renderer/world/cube.hpp
  src/CMakeLists.txt
Labels: feat:ci
