Repository inexorgame/vulkan-renderer, pull requests merged in 2022-10, with the labels that each got.

#496 [tests] Fix physical device selection tests
  tests/gpu-selection/selection.cpp
Labels: org:triage

#494 [*] Replace deprecated Vulkan version macro
  src/vulkan-renderer/application.cpp
  src/vulkan-renderer/vk_tools/gpu_info.cpp
  src/vulkan-renderer/wrapper/instance.cpp
Labels: org:triage

#503 [device] Implement find_queue_family_index_if
  include/inexor/vulkan-renderer/settings_decision_maker.hpp
  include/inexor/vulkan-renderer/vk_tools/enumerate.hpp
  include/inexor/vulkan-renderer/wrapper/device.hpp
  src/vulkan-renderer/application.cpp
  src/vulkan-renderer/settings_decision_maker.cpp
  src/vulkan-renderer/vk_tools/enumerate.cpp
  src/vulkan-renderer/wrapper/device.cpp
Labels: cat:refactor

#504 [representation] Fix msvc warning
  include/inexor/vulkan-renderer/vk_tools/representation.hpp
  src/vulkan-renderer/vk_tools/representation.cpp
Labels: prio:low, cat:refactor
