Repository inexorgame/vulkan-renderer, pull requests merged in 2023-06, with the labels that each got.

#540 [workflows] Fix automatic release generation when a pull request is merged into main
  .github/workflows/release.yml
Labels: prio:high, cat:bug, feat:ci

#541 [workflows] Fix automatic release generation
  .github/workflows/release.yml
Labels: prio:high, cat:bug, feat:ci

#542 [workflows] Fix automatic release generation
  .github/workflows/release.yml
Labels: prio:high, cat:bug, feat:ci

#544 [workflows] Fix automatic release generation
  .github/workflows/release.yml
Labels: prio:high, cat:bug, feat:ci

#545 [workflows] Fix automatic release generation
  .github/workflows/build.yml
Labels: prio:high, cat:bug, feat:ci

#549 Delete gpu_info entirely
  documentation/source/development/debugging/cla.rst
  include/inexor/vulkan-renderer/renderer.hpp
  include/inexor/vulkan-renderer/vk_tools/gpu_info.hpp
  src/CMakeLists.txt
  src/vulkan-renderer/application.cpp
  src/vulkan-renderer/vk_tools/gpu_info.cpp
Labels: cat:bug, cat:refactor

#550 [ci] Rename devel to nightly release
  .github/workflows/build.yml
  .github/workflows/release.yml
Labels: feat:ci
